### ISSUE TITLE
[enhancement] Error message should be more visible

### ISSUE THREAD

**Issue by overeha** [code4romania/crestem-ong#10]
When I am performing an evaluation as an employee if I did not reply to all of the questions, if I click Next/Continue the unanswered question gets the first checkbox highlighted in blue. 
Three out of four people performing the test did not notice the highlight. 

Expected behaviour: 
If a user misses a question the question text should turn red or get a red underline or the entire question should be left as is but placed in red square.

**Comment by cipick** [comment]
<img width="1393" alt="Screenshot 2023-04-04 at 20 59 52" src="https://user-images.githubusercontent.com/6429818/229878587-3fe91129-e1a7-4e7c-a1e9-3188fcc4f8c8.png">
this is fine?

**Comment by overeha** [comment]
Perfect
