### ISSUE TITLE
[to implement] Email texts

### ISSUE THREAD

**Issue by overeha** [code4romania/crestem-ong#12]
<html>
<body>
<google-sheets-html-origin><style type="text/css"></style>

Pagina/email | Comments | Subject email | Text final
-- | -- | -- | --
Email pe care il primeste anagjatul ONG-ului cand este invitat sa completeze chestionarul |   | Salut! Ai fost invitat să răspunzi la un chestionar Crestem.ONG | Bună, Ai primit o invitație să răspunzi la un chestionar de evaluare al organizației [nume organizatie]. Acest chestionar vă ajută să identificați nevoile, punctele tari și cele de îmbunătățit ale ONGului din mai multe perspective de dezvoltare organizațională.Deadline-ul de completare pentru chestionar este: [end_date]Link: [user_link]Mulțumim! Echipa Creștem.ONG
Email pe care îl primește administratorul ONG cand toata lumea invitata a terminat de completat chestionarele |   | Salut! Toți membrii organizației au completat chestionarele transmise | Bună, Toate persoanele invitate de tine să completeze chestionarul de dezvoltare organizațională a finalizat. Poți intra în contul tău să finalizezi evaluarea și să vezi rezultatele:[link pagina login]O zi frumoasă! Echipa Creștem.ONG
Email pe care îl primește administratorul ONG cu o zi inainte de deadline-ul de completare (1 day before end_date) |   | Salut! A mai rămas o zi pînă la deadline | Bună, Mai e o singură zi în care persoanele din organizația ta pot completa chestionarul de evaluare. Toți au primit o notificare automată ca reminder pentru a finaliza completarea chestionarului. Dacă ai nevoie de mai mult timp, poți intra în contul tău de organizație și poți prelungi termenul de completare sau poți lua legătura cu echipa noastră pentru a te ajuta în acest proces.   [link login]O zi frumoasă! Echipa Creștem.ONG
Email pe care îl primește angajatul cu o zi inainte de deadline-ul de completare (1 day before end_date) | Nu exista | Salut! A mai rămas o zi pînă la deadline | Bună, Mai e o singură zi în care poți completa chestionarul de evaluare a [nume organizatie]. Dacă nu ai timp suficient, ia legătura cu organizația ta și solicită o extindere a termenului limită. O zi frumoasă! Echipa Creștem.ONG
Email pe care il primeste echipa CrestemONG cand a fost creat un nou cont de ONG in sistem | Catre: contact@crestem.ong | Cont nou pe Crestem.ONG | Bună, [nume organizatie] a deschis un cont de organizație pe Creștem.ONG.O zi frumoasă! Echipa Creștem.ONG
  |   |   |  
Email pentru administratorul ONG când se înscrie în sistem |   | Bine ai venit! | Felicitări, contul tău pe Creștem.ONG a fost creat cu succes! Următorul pas este să stabilești perioada de evaluare a organizației tale și să inviți persoanele pe care vrei să le implici în analiză: pot fi membri, angajați, colaboratori (permanenți), membri ai structurii de guvernanță (board/ consiliu director), voluntari și/ sau beneficiari activ implicați în organizație (implicați în activități ce țin de management și/ sau guvernanță). Nu uita să incluzi și adresa ta în listă pentru a răspunde la rândul tău întrebărilor.Veți avea la dispoziție maxim o lună pentru a completa chestionarul. Vei putea apoi închide evaluarea tot din contul tău și vei primi un raport cu media răspunsurilor și recomandări de resurse pentru dezvoltarea voastră organizațională. Dacă sunteți înscriși într-unul dintre programele noastre de dezvoltare, vei primi tot atunci detalii despre asistența personalizată.  Pentru orice întrebări sau nelămuriri, nu ezita să ne contactezi pe chat-ul de pe site sau la contact@crestem.ong. Succes! Echipa Creștem.ONG
  |   |   |  
Email de conectare admin ONG cu o persoana resursa | se trimite catre persoana resursa, catre ong, catre contact@crestem.ong | Salut! Ai trecut la o nouă etapă | Bună, În urma evaluării organizației [nume organizatie] vă invităm să vă conectați pentru procesul de coaching.Persoana resursă va trimite în scurt timp un mesaj cu intervaluri orare disponibile și detalii despre modul de lucru. O zi frumoasă! Echipa Creștem.ONG

</body>
</html>

**Comment by cipick** [comment]
Will need email subject as well please 😁

**Comment by overeha** [comment]
actualizat mailurile in tabel mai sus
