### ISSUE TITLE
Add facebook chat plugin

### ISSUE THREAD

**Issue by cipick** [code4romania/crestem-ong#18]
We have the code

    <div id="fb-root"></div>

    
    <div id="fb-customer-chat" class="fb-customerchat">
    </div>

    <script>
      var chatbox = document.getElementById('fb-customer-chat');
      chatbox.setAttribute("page_id", "158962987472579");
      chatbox.setAttribute("attribution", "biz_inbox");
    </script>

    
    <script>
      window.fbAsyncInit = function() {
        FB.init({
          xfbml            : true,
          version          : 'v16.0'
        });
      };

      (function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = 'https://connect.facebook.net/ro_RO/sdk/xfbml.customerchat.js';
        fjs.parentNode.insertBefore(js, fjs);
      }(document, 'script', 'facebook-jssdk'));
    </script>

![image](https://user-images.githubusercontent.com/45068169/233077062-2781c598-e023-492e-b36f-b629a1bd9655.png)

**Comment by overeha** [comment]
here it is!
