### ISSUE TITLE
[Evaluări] evaluations with no NGO associated 

### ISSUE THREAD

**Issue by teodoranegru** [code4romania/crestem-ong#30]
In the 'Evaluări' table there are evaluations that are not linked to any organisation. This can not be possible because only organisations can create evaluations. 
To investigate why that happens

![image](https://github.com/code4romania/crestem-ong/assets/102228836/59983e84-0b66-4529-bb09-d9f228f5b53f)

**Comment by cipick** [comment]
they were created from admin panel by me, i have deleted them and also they will be not displayed if the ong name is missing
