### ISSUE TITLE
[Acasă] error at accessing registration form

### ISSUE THREAD

**Issue by teodoranegru** [code4romania/crestem-ong#34]
**Describe the bug:**
When you click on 'Înregistrează-te' button from home page, it displays the error below. 

![image](https://github.com/code4romania/crestem-ong/assets/102228836/5828a8f7-d293-4469-859b-6a89834fe822)

**To reproduce:*
1. Go to https://crestem.ong/ro
2. Click on 'Înregistrează-te' button 
3. Notice the error displayed

![image](https://github.com/code4romania/crestem-ong/assets/102228836/91a857a8-30df-4f90-86e5-4ddb9b7d11e7)

**Expected behavior:**
When the user click on 'Înregistrează-te' button it should take him to the registration form (here - https://app.crestem.ong/register)

**Comment by cipick** [comment]
@andreiio this is on website factory side

**Comment by teodoranegru** [comment]
Am rezolvat eu din Admin WF, merge acum
