### ISSUE TITLE
[Registration] change 'Județ' and 'Localitate' fields type 

### ISSUE THREAD

**Issue by teodoranegru** [code4romania/crestem-ong#44]
In the [registration form ](https://app.crestem.ong/register), the fields 'Județ' and Localitate' are text input. Change field types from text input to single select.

**Comment by mirunaioana-msc** [comment]
This issue is high priority because on the Organizatii page, we need filters for both Localitate & Judet.

**Comment by teodoranegru** [comment]
Can we have the values from Localitate field in alphabetical order?
