### ISSUE TITLE
[Admin ONG/Evaluare ONG] miscalculation of 'Perioadă de completare' 

### ISSUE THREAD

**Issue by teodoranegru** [code4romania/crestem-ong#45]
**Describe the bug**
The completion period is calculated taking into consideration the starting date 'Dată început' and the finish date 'Dată final'. Although this is the default, the Admin ONG can manually end an evaluation by clicking on the 'Finalizează evaluarea' button. If that is the case, the finish date by which the completion period is calculated should be the date when the Admin manually ended the evaluation. Now, the completion period is calculated only by value chosen in 'Dată final' field, even if the Admin manually ends the evaluation. 

**Expected behavior**
If the user Admin ONG manually ends the evaluation, the finish date by which the completion period is calculated should be the date when the Admin manually ended the evaluation.

**Comment by cipick** [comment]
We need to add a closedAt: timestamp to all reports so we can proper calculate the period if the user click finish report before deadline
