### ISSUE TITLE
[General] change the default sender of email from 'noreply..' to 'crestem.ong@fdsc.ro'

### ISSUE THREAD

**Issue by teodoranegru** [code4romania/crestem-ong#49]
Verifica te rog si documentul https://docs.google.com/document/d/1Mr8ONNpvLYLXFCdMzmJNaP4kXz3JaGeJo_Ivqb0JifM/edit?usp=sharing. Acolo s-a mai disuctat despre asta si ti-am lasta un comment.

**Comment by teodoranegru** [comment]
![image](https://github.com/code4romania/crestem-ong/assets/102228836/8d96384e-5117-47c4-824f-62152c071d61)

**Comment by mirunaioana-msc** [comment]
We are aware that we cannot change the sender, but can we at least change the alias of the sender?
