### ISSUE TITLE
[Admin ONG/Evaluare ONG] link from reminder email does not work

### ISSUE THREAD

**Issue by teodoranegru** [code4romania/crestem-ong#52]
![image](https://github.com/code4romania/crestem-ong/assets/102228836/6531dbe8-d27b-41ea-9b8b-413b476b4ec1)

![image](https://github.com/code4romania/crestem-ong/assets/102228836/c74772f3-40d2-421b-8606-9845f9fbbb5c)

**Comment by mirunaioana-msc** [comment]
Fixed from Strapi
