### ISSUE TITLE
[Admin FDSC/Adăugare persoană resursă] no confirmation message after sending the invite 

### ISSUE THREAD

**Issue by teodoranegru** [code4romania/crestem-ong#53]
**Describe the issue**
When you click on the 'Salvează' button after filling in the _Adaugă persoană resursă_ form, there is no confirmation message displayed and the page remains in edit mode. Even though the account is created and the invite is sent to the corresponding email address, the user does not receive any sign or message that informs them that the action was successfully completed. 

**To Reproduce**
1. Log in as Admin FDSC user type
2. Go to 'Persoane resursă' page from the top main navigation
3. Click on the 'Adaugă persoană resursă' button
4. Fill in the form 
5. Click on the 'Salvează' button
6. Notice the behavior 

**Expected behavior**
When the user clicks on the 'Salvează' button, the user should be returned to the ['Persoane resursă' page](https://app.crestem.ong/mentors), and a confirmation message should be displayed.

**Comment by cipick** [comment]
![Screenshot 2023-10-19 at 00 53 57](https://github.com/code4romania/crestem-ong/assets/6429818/c7a8951c-8eaf-4507-a031-f90c69a200db)
