### ISSUE TITLE
[Persoană resursă/ Setare parolă]  error at setting a password

### ISSUE THREAD

**Issue by teodoranegru** [code4romania/crestem-ong#54]
**Describe the bug**
As a Persoană resursă user type, when you try to set a password (after accessing the link from the invitation received via email), it displays an error, and you can't set the password to access your account. Even if you try with multiple types of passwords, it displays the same error. 

![image](https://github.com/code4romania/crestem-ong/assets/102228836/4ecdae35-e8d9-4f75-aaca-aa737823674a)

**Comment by cipick** [comment]
fixed 👍
