### ISSUE TITLE
[Admin FDSC/Organizații] implement add organisation to the platform 

### ISSUE THREAD

**Issue by teodoranegru** [code4romania/crestem-ong#56]
Implements the feature of adding organizations to the platform ([see design of the page here](https://www.figma.com/file/EeUtizbTE8Bkqhjx70CwOB/Cre%C8%99tem-ONG?type=design&node-id=1511-26905&mode=design&t=oEbcxZsWKVjZzCLF-4))

**Comment by cipick** [comment]
duplicated https://github.com/code4romania/crestem-ong/issues/48
