### ISSUE TITLE
[enhancement] Warning before displaying final results

### ISSUE THREAD

**Issue by overeha** [code4romania/crestem-ong#6]
Currently when an NGO clicks on "Finalize evaluation" the action takes place instantly.

Expected behaviour: 
When "Finalize evaluation" gets clicked --> modal/pop-up shows up ”Ești sigur că vrei să finalizezi evaluarea? Dacă finalizezi acum, persoanele care nu au răspuns la chestionarul de evaluare nu vor putea să mai completeze. Asigură-te că ai toate răspunsurile înainte de a face această acțiune” + two options: Renunță / Finalizează evaluarea

**Comment by cipick** [comment]
i think will need designs for it or at least choose a modal from here
https://tailwindui.com/components/application-ui/overlays/modals

**Comment by overeha** [comment]
use this model

<img width="531" alt="Screenshot 2023-04-04 at 21 49 51" src="https://user-images.githubusercontent.com/45068169/229898898-3a55ea59-744b-43b3-93ff-0ee8200c25fa.png">

**Comment by overeha** [comment]
<img width="1368" alt="Screenshot 2023-04-04 at 22 25 05" src="https://user-images.githubusercontent.com/45068169/229898996-6c8b1530-8568-4175-ba57-7d944f4621dc.png">
