### ISSUE TITLE
[Admin ONG/Persoane resursă] implement the send message to resource person feature

### ISSUE THREAD

**Issue by teodoranegru** [code4romania/crestem-ong#64]
The Admin ONG user should be able to email the resource person. There should be a 'Trimite mesaj' button that automatically sends a standardized message to the resource person ([see design and interaction notes here](https://www.figma.com/file/EeUtizbTE8Bkqhjx70CwOB/Cre%C8%99tem-ONG?type=design&node-id=1694-37628&mode=design&t=n84o6A92aLuMVw5U-4))

**Comment by cipick** [comment]
this is partially done, i will need a success message and a generic error message. also we need to ask for mail content
