### ISSUE TITLE
[Persoană resursă/Profilul meu] implement the user's profile page

### ISSUE THREAD

**Issue by teodoranegru** [code4romania/crestem-ong#65]
The resource person user should be able to view and edit their profile information on an individual page. ([see design here](https://www.figma.com/file/EeUtizbTE8Bkqhjx70CwOB/Cre%C8%99tem-ONG?type=design&node-id=1681-27866&mode=design&t=n84o6A92aLuMVw5U-4))

**Comment by cipick** [comment]
<img width="1232" alt="Screenshot 2023-10-22 at 23 26 42" src="https://github.com/code4romania/crestem-ong/assets/6429818/d30c0d98-21ca-48b3-942b-501538328609">
<img width="1428" alt="Screenshot 2023-10-22 at 23 27 36" src="https://github.com/code4romania/crestem-ong/assets/6429818/47c0eb33-85e6-48cb-a3eb-afdc1c0568ad">
