### ISSUE TITLE
[Persoană resursă/Evaluare ONG] implement the Evaluare ONG page 

### ISSUE THREAD

**Issue by teodoranegru** [code4romania/crestem-ong#66]
The resource person user type should be able to view the evaluation form. Implement the Evaluare ONG page that displays the evaluation form. ([see design here](https://www.figma.com/file/EeUtizbTE8Bkqhjx70CwOB/Cre%C8%99tem-ONG?type=design&node-id=1686-28036&mode=design&t=n84o6A92aLuMVw5U-4))

**Comment by mirunaioana-msc** [comment]
This seems done
