### ISSUE TITLE
[Membru ONG/Chestionar evaluare] error at accessing the evaluation form 

### ISSUE THREAD

**Issue by teodoranegru** [code4romania/crestem-ong#67]
When the Admin ONG user creates a new evaluation in the platform, they invite the organization's members to fill in the evaluation form via email. As an NGO member, you receive an email with the link to the evaluation form. 
**The link to the evaluation form does not work** 

![image](https://github.com/code4romania/crestem-ong/assets/102228836/15403a91-080d-474d-9fe8-cea3606ab6d1)

**Comment by cipick** [comment]
seems to work https://app.crestem.ong/evaluation/66?email=teodora.negru%40code4.ro
