### ISSUE TITLE
[Admin ONG/Log in] log in is not working

### ISSUE THREAD

**Issue by teodoranegru** [code4romania/crestem-ong#69]
As an Admin ONG user type, I receive this error when I try to log in, even if my credentials are correct. 

![image](https://github.com/code4romania/crestem-ong/assets/102228836/aed9d6e0-c50e-479a-a387-0e2e8eefd1f5)

**Comment by cipick** [comment]
can't reproduce

**Comment by teodoranegru** [comment]
si mie imi merge acum
