### ISSUE TITLE
[enhancement] Dimensions displays whould be listed by score

### ISSUE THREAD

**Issue by overeha** [code4romania/crestem-ong#7]
In the Evaluation results page the percentages should be visible and the list of dimensions should not follow the questionnaire but the scored achieved. 

The dimensions should be ordered from lowest score to highest score. 

![image](https://user-images.githubusercontent.com/45068169/228509865-f634bf1c-7c33-4f79-86a9-ea861f9812b9.png)

**Comment by cipick** [comment]
so in your case where you don't have any evaluation completed no evaluation should be displayed?

**Comment by overeha** [comment]
When there is no evaluation completed it means i cannot click on FInalize, so I do not get to this screen before I have at least one evaluation done by a member. At least that is how it is now.
