### ISSUE TITLE
[General/Registration] Translate unique ONG identification number registration error

### ISSUE THREAD

**Issue by teodoranegru** [code4romania/crestem-ong#70]
The registration feature using the [registration form](https://app.crestem.ong/register) needs to be fixed. When you click on the 'Salvează' button, nothing happens. 

Expected behavior: 
- The user fills in all the fields from _Informații obligatorii despre ONG_ section
- Based on the value entered in 'CIF-ul organizației' field, the database checks if the organization is already registered or not => if yes - it displays an error 'Organizație deja înregistrată în platformă'; if not - the account/organization is created in db and the success email is sent to the email entered in the 'Email organizație' field

**Comment by cipick** [comment]
fixed
