### ISSUE TITLE
[Admin FDSC/ Organizații] error at accesing the 'Organizații' page

### ISSUE THREAD

**Issue by teodoranegru** [code4romania/crestem-ong#73]
Error at accessing the ''[Organizații](https://app.crestem.ong/users)'' page 

![image](https://github.com/code4romania/crestem-ong/assets/102228836/f72a764f-ee97-4384-9ef8-dbc6e4883f1b)

**Comment by cipick** [comment]
are you able to still reproduce this? it works for me 😕

**Comment by teodoranegru** [comment]
it works now
