### ISSUE TITLE
[Admin ONG/ Evaluation form] cannot open the evaluation form if logged in as Admin FDSC from the same browser

### ISSUE THREAD

**Issue by teodoranegru** [code4romania/crestem-ong#78]
If you are logged in as Admin ONG and try to open an evaluation in the same browser, it will display this error:

![image](https://github.com/code4romania/crestem-ong/assets/102228836/9f07af6a-96dd-4121-ad13-9bdc0d0f3781)

To investigate if we can solve this.

**Comment by mirunaioana-msc** [comment]
this situation shouldn't happen in a normal setting.
