### ISSUE TITLE
[enhancement] Add organization name in the upper right corner

### ISSUE THREAD

**Issue by overeha** [code4romania/crestem-ong#8]
Display Organization name next to the organization logo in the upper right corner

![image](https://user-images.githubusercontent.com/45068169/228512396-c8176b53-26bd-4be9-afc0-3a9d6661b88f.png)

**Comment by cipick** [comment]
<img width="232" alt="Screenshot 2023-04-04 at 21 16 54" src="https://user-images.githubusercontent.com/6429818/229882235-17e4dab7-7803-4b04-8bdc-10a5fb9ba252.png">

**Comment by overeha** [comment]
Amazing!
