### ISSUE TITLE
[Admin FDSC/Evaluări/Evaluare individuală/ Vezi răspunsuri] the values entered in the text filed are not being saved

### ISSUE THREAD

**Issue by teodoranegru** [code4romania/crestem-ong#81]
In the evaluation form, there is a mandatory text field for each dimension. Even though it is mandatory, the values entered in the field are not saved or displayed in the individual evaluation submission (see screenshots below). 

![image](https://github.com/code4romania/crestem-ong/assets/102228836/2f312adc-6478-43fc-9e0a-c64dbb06cd5b)

![image](https://github.com/code4romania/crestem-ong/assets/102228836/cfa109ab-90ea-4196-ba04-976a8bab693c)

**Comment by cipick** [comment]
<img width="880" alt="Screenshot 2023-10-04 at 00 48 05" src="https://github.com/code4romania/crestem-ong/assets/6429818/12f6a0ba-3e7b-47f2-aea4-0f98744970ca">
Fixed 👍 You can check it here https://crestem-ong-git-81-admin-fdscevalurievaluar-08a1d1-code4romania.vercel.app/evaluation/33?email=Charliedelsh@gmail.com if you login with a FDSC account
