### ISSUE TITLE
[enhancement] Add My Organization to the user menu

### ISSUE THREAD

**Issue by overeha** [code4romania/crestem-ong#9]
Add a new link in the user menu for the user to be able to go back to his home screen where he sees all his organisation's evaluation. 

Add this link before Sign Out
![image](https://user-images.githubusercontent.com/45068169/228512783-da5dee00-dad6-4386-96ec-7de6ef889467.png)

Should be redirected here 
![image](https://user-images.githubusercontent.com/45068169/228512884-60e90fd4-2606-4a8c-bdd5-a9e2748bdc00.png)

**Comment by cipick** [comment]
<img width="220" alt="Screenshot 2023-04-04 at 21 14 20" src="https://user-images.githubusercontent.com/6429818/229881707-83f56491-0913-41a9-bb97-b1b34721f7e2.png">

**Comment by overeha** [comment]
Great
